services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: noclunetwork:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    networks:
      - default
      - noclulabscom

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - noclunetwork_redisdata:/data
    networks:
      - default

networks:
  default:
  noclulabscom:
    external: true
    name: noclulabscom_default

volumes:
  noclunetwork_redisdata:
